const shippingFees = [
    {
        city: "Bacoor", 
        barangays: [
            { name: "Alima", fee: 40 },
            { name: "Aniban 1", fee: 40 },
            { name: "Aniban 2", fee: 40 },
            { name: "Aniban 3", fee: 40 },
            { name: "Aniban 4", fee: 40 },
            { name: "Aniban 5", fee: 40 },
            { name: "Banalo", fee: 40 },
            { name: "Bayanan", fee: 40 },
            { name: "Campo Santo", fee: 40 },
            { name: "Daang Bukid", fee: 40 },
            { name: "Digma", fee: 40 },
            { name: "Dulong Bayan", fee: 40 },
            { name: "Habay 1", fee: 40 },
            { name: "Habay 2", fee: 40 },
            { name: "Kaingin", fee: 40 },
            { name: "Ligas 1", fee: 40 },
            { name: "Ligas 2", fee: 40 },
            { name: "Mabolo 1", fee: 40 },
            { name: "Mambog 1", fee: 40 },
            { name: "Mambog 2", fee: 40 },
            { name: "Mambog 3", fee: 40 },
            { name: "Mambog 4", fee: 40 },
            { name: "Mambog 5", fee: 40 },
            { name: "Molino 1", fee: 40 },
            { name: "Molino 2", fee: 40 },
            { name: "Molino 3", fee: 40 },
            { name: "Molino 4", fee: 40 },
            { name: "Molino 5", fee: 40 },
            { name: "Molino 6", fee: 40 },
            { name: "Molino 7", fee: 40 },
            { name: "Niog 1", fee: 40 },
            { name: "Niog 2", fee: 40 },
            { name: "Niog 3", fee: 40 },
            { name: "P. F. Espiritu 1", fee: 40 },
            { name: "P. F. Espiritu 2", fee: 40 },
            { name: "P. F. Espiritu 3", fee: 40 },
            { name: "P. F. Espiritu 4", fee: 40 },
            { name: "P. F. Espiritu 5", fee: 40 },
            { name: "P. F. Espiritu 6", fee: 40 },
            { name: "P. F. Espiritu 7", fee: 40 },
            { name: "P. F. Espiritu 8", fee: 40 },
            { name: "Queens Row Central", fee: 40 },
            { name: "Queens Row East", fee: 40 },
            { name: "Queens Row West", fee: 40 },
            { name: "Real 1", fee: 40 },
            { name: "Real 2", fee: 40 },
            { name: "Salinas 1", fee: 40 },
            { name: "Salinas 2", fee: 40 },
            { name: "Salinas 3", fee: 40 },
            { name: "Salinas 4", fee: 40 },
            { name: "San Nicolas 1", fee: 40 },
            { name: "San Nicolas 2", fee: 40 },
            { name: "San Nicolas 3", fee: 40 },
            { name: "Sinegluelasan", fee: 40 },
            { name: "Tabala 1", fee: 40 },
            { name: "Tabala 2", fee: 40 },
            { name: "Tabala 3", fee: 40 },
            { name: "Tabala 4", fee: 40 },
            { name: "Tabala 5", fee: 40 },
            { name: "Tabala 6", fee: 40 },
            { name: "Tabala 7", fee: 40 },
            { name: "Zapote 1", fee: 40 },
            { name: "Zapote 2", fee: 40 },
            { name: "Zapote 3", fee: 40 },
            { name: "Zapote 4", fee: 40 },
            { name: "Zapote 5", fee: 40 }
        ]
    },
    {
        city: "Dasmarinas",
        barangays: [
            { name: "Burol", fee: 41 },
            { name: "Burol 1", fee: 41 },
            { name: "Burol 2", fee: 41 },
            { name: "Burol 3", fee: 41 },
            { name: "Datu Esmael", fee: 41 },
            { name: "Emmanue; Bergado", fee: 41 },
            { name: "Fatima 1", fee: 41 },
            { name: "Fatima 2", fee: 41 },
            { name: "Fatima 3", fee: 41 },
            { name: "H-2", fee: 41 },
            { name: "Langkaan 1", fee: 41 },
            { name: "Langkaan 2", fee: 41 },
            { name: "Luzviminda 1", fee: 41 },
            { name: "Luzviminda 2", fee: 41 },
            { name: "Paliparan 1", fee: 41 },
            { name: "Paliparan 2", fee: 41 },
            { name: "Paliparan 3", fee: 41 },
            { name: "Sabang ", fee: 41 },
            { name: "Saint Peter 1", fee: 41 },
            { name: "Saint Peter 2", fee: 41 },
            { name: "Salawag", fee: 41 },
            { name: "Salitran 1", fee: 41 },
            { name: "Salitran 2", fee: 41 },
            { name: "Salitran 3", fee: 41 },
            { name: "Salitran 4", fee: 41 },
            { name: "Sampaloc 1", fee: 41 },
            { name: "Sampaloc 2", fee: 41 },
            { name: "Sampaloc 3", fee: 41 },
            { name: "Sampaloc 4", fee: 41 },
            { name: "Sampaloc 5", fee: 41 },
            { name: "San Agustin 1", fee: 41 },
            { name: "San Agustin 2", fee: 41 },
            { name: "San Agustin 3", fee: 41 },
            { name: "San Andres 1", fee: 41 },
            { name: "San Andres 2", fee: 41 },
            { name: "San Antonio de Pauda 1", fee: 41 },
            { name: "San Antonio de Pauda 2", fee: 41 },
            { name: "San Dionisio", fee: 41 },
            { name: "San Esteban", fee: 41 },
            { name: "San Francisco 1", fee: 41 },
            { name: "San Francisco 2", fee: 41 },
            { name: "San Isidro Labrado 1", fee: 41 },
            { name: "San Isidro Labrado 2", fee: 41 },
            { name: "San Jose", fee: 41 },
            { name: "San Juan", fee: 41 },
            { name: "San Lorenzo Ruiz 1", fee: 41 },
            { name: "San Lorenzo Ruiz 2", fee: 41 },
            { name: "San Mateo", fee: 41 },
            { name: "San Miguel 1", fee: 41 },
            { name: "San Miguel 2", fee: 41 },
            { name: "San Nicolas 1", fee: 41 },
            { name: "San Nicolas 2", fee: 41 },
            { name: "San Roque", fee: 41 },
            { name: "San Simon", fee: 41 },
            { name: "Santa Christina 1", fee: 41 },
            { name: "Santa Cruz 1", fee: 41 },
            { name: "Santa Cruz 2", fee: 41 },
            { name: "Santa Fe", fee: 41 },
            { name: "Santa Lucia", fee: 41 },
            { name: "Santa Maria", fee: 41 },
            { name: "Santo Cristo", fee: 41 },
            { name: "Santo Nino 1", fee: 41 },
            { name: "Santo Nino 2", fee: 41 },
            { name: "Victoria Reyes", fee: 41 },
            { name: "Zone 1", fee: 41 },
            { name: "Zone 1-B", fee: 41 },
            { name: "Zone 2", fee: 41 },
            { name: "Zone 3", fee: 41 },
            { name: "Zone 4", fee: 41 }

            
        ]
    },
    {
        city: "Imus",
        barangays: [
            { name: "Alapan 1-A", fee: 42 },
            { name: "Alapan 1-B", fee: 42 },
            { name: "Alapan 1-C", fee: 42 },
            { name: "Alapan 2-A", fee: 42 },
            { name: "Alapan 2-B", fee: 42 },
            { name: "Anabu 1-A", fee: 42 },
            { name: "Anabu 1-B", fee: 42 },
            { name: "Anabu 1-C", fee: 42 },
            { name: "Anabu 1-D", fee: 42 },
            { name: "Anabu 1-E", fee: 42 },
            { name: "Anabu 1-F", fee: 42 },
            { name: "Anabu 1-G", fee: 42 },
            { name: "Anabu 2-A", fee: 42 },
            { name: "Anabu 2-B", fee: 42 },
            { name: "Anabu 2-C", fee: 42 },
            { name: "Anabu 2-D", fee: 42 },
            { name: "Anabu 2-E", fee: 42 },
            { name: "Anabu 2-F", fee: 42 },
            { name: "Bayan Luma 1", fee: 42 },
            { name: "Bayan Luma 2", fee: 42 },
            { name: "Bayan Luma 3", fee: 42 },
            { name: "Bayan Luma 4", fee: 42 },
            { name: "Bayan Luma 5", fee: 42 },
            { name: "Bayan Luma 6", fee: 42 },
            { name: "Bayan Luma 7", fee: 42 },
            { name: "Bayan Luma 8", fee: 42 },
            { name: "Bayan Luma 9", fee: 42 },
            { name: "Bucandala 1", fee: 42 },
            { name: "Bahay na Tubig", fee: 42 },
            { name: "Carsadang Bago 1", fee: 42 },
            { name: "Carsadang Bago 2", fee: 42 },
            { name: "Magdalo", fee: 42 },
            { name: "Maharlika", fee: 42 },
            { name: "Malagasang 1-A", fee: 42 },
            { name: "Malagasang 1-B", fee: 42 },
            { name: "Malagasang 1-C", fee: 42 },
            { name: "Malagasang 1-D", fee: 42 },
            { name: "Malagasang 1-F", fee: 42 },
            { name: "Malagasang 1-G", fee: 42 },
            { name: "Malagasang 2-A", fee: 42 },
            { name: "Malagasang 2-B", fee: 42 },
            { name: "Malagasang 2-C", fee: 42 },
            { name: "Malagasang 2-E", fee: 42 },
            { name: "Malagasang 2-F", fee: 42 },
            { name: "Malagasang 2-G", fee: 42 },
            { name: "Mariano Espeleta 1", fee: 42 },
            { name: "Mariano Espeleta 2", fee: 42 },
            { name: "Mariano Espeleta 3", fee: 42 },
            { name: "Medicion 1-A", fee: 42 },
            { name: "Medicion 1-B", fee: 42 },
            { name: "Medicion 1-C", fee: 42 },
            { name: "Medicion 1-D", fee: 42 },
            { name: "Medicion 2-A", fee: 42 },
            { name: "Medicion 2-B", fee: 42 },
            { name: "Medicion 2-C", fee: 42 },
            { name: "Medicion 2-D", fee: 42 },
            { name: "Medicion 2-E", fee: 42 },
            { name: "Medicion 2-F", fee: 42 },
            { name: "Pag-asa 1", fee: 42 },
            { name: "Pag-asa 2", fee: 42 },
            { name: "Pag-asa 3", fee: 42 },
            { name: "Palico 1", fee: 42 },
            { name: "Palico 2", fee: 42 },
            { name: "Palico 3", fee: 42 },
            { name: "Palico 4", fee: 42 },
            { name: "Pasong Buaya 1", fee: 42 },
            { name: "Pasong Buaya 2", fee: 42 },
            { name: "Pinagbuklod", fee: 42 },
            { name: "Poblacion 1-A", fee: 42 },
            { name: "Poblacion 1-B", fee: 42 },
            { name: "Poblacion 1-C", fee: 42 },
            { name: "Poblacion 2-A", fee: 42 },
            { name: "Poblacion 2-B", fee: 42 },
            { name: "Poblacion 3-A", fee: 42 },
            { name: "Poblacion 3-B", fee: 42 },
            { name: "Poblacion 4-A", fee: 42 },
            { name: "Poblacion 4-B", fee: 42 },
            { name: "Poblacion 4-C", fee: 42 },
            { name: "Poblacion 4-D", fee: 42 },
            { name: "Tanzang Luma 1", fee: 42 },
            { name: "Tanzang Luma 2", fee: 42 },
            { name: "Tanzang Luma 3", fee: 42 },
            { name: "Tanzang Luma 4", fee: 42 },
            { name: "Tanzang Luma 5", fee: 42 },
            { name: "Tanzang Luma 6", fee: 42 },
            { name: "Toclong 1-A", fee: 42 },
            { name: "Toclong 1-B", fee: 42 }
        ]
    },
    {
        city: "Cavite City",
        barangays: [
            { name: "Barangay 1", fee: 43 },
            { name: "Barangay 10", fee: 43 },
            { name: "Barangay 10-A", fee: 43 },
            { name: "Barangay 11", fee: 43 },
            { name: "Barangay 12", fee: 43 },
            { name: "Barangay 13", fee: 43 },
            { name: "Barangay 14", fee: 43 },
            { name: "Barangay 15", fee: 43 },
            { name: "Barangay 16", fee: 43 },
            { name: "Barangay 17", fee: 43 },
            { name: "Barangay 18", fee: 43 },
            { name: "Barangay 19", fee: 43 },
            { name: "Barangay 2", fee: 43 },
            { name: "Barangay 20", fee: 43 },
            { name: "Barangay 21", fee: 43 },
            { name: "Barangay 22", fee: 43 },
            { name: "Barangay 22-A", fee: 43 },
            { name: "Barangay 23", fee: 43 },
            { name: "Barangay 24", fee: 43 },
            { name: "Barangay 25", fee: 43 },
            { name: "Barangay 26", fee: 43 },
            { name: "Barangay 27", fee: 43 },
            { name: "Barangay 28", fee: 43 },
            { name: "Barangay 29-A", fee: 43 },
            { name: "Barangay 3", fee: 43 },
            { name: "Barangay 31", fee: 43 },
            { name: "Barangay 31", fee: 43 },
            { name: "Barangay 32", fee: 43 },
            { name: "Barangay 33", fee: 43 },
            { name: "Barangay 34", fee: 43 },
            { name: "Barangay 35", fee: 43 },
            { name: "Barangay 36", fee: 43 },
            { name: "Barangay 36-A", fee: 43 },
            { name: "Barangay 37", fee: 43 },
            { name: "Barangay 37-A", fee: 43 },
            { name: "Barangay 38", fee: 43 },
            { name: "Barangay 38-A", fee: 43 },
            { name: "Barangay 39", fee: 43 },
            { name: "Barangay 40", fee: 43 },
            { name: "Barangay 41", fee: 43 },
            { name: "Barangay 42", fee: 43 },
            { name: "Barangay 42-A", fee: 43 },
            { name: "Barangay 42-B", fee: 43 },
            { name: "Barangay 42-C", fee: 43 },
            { name: "Barangay 43", fee: 43 },
            { name: "Barangay 44", fee: 43 },
            { name: "Barangay 45", fee: 43 },
            { name: "Barangay 45-A", fee: 43 },
            { name: "Barangay 46", fee: 43 },
            { name: "Barangay 47", fee: 43 },
            { name: "Barangay 47-A", fee: 43 },
            { name: "Barangay 47-B", fee: 43 },
            { name: "Barangay 48", fee: 43 },
            { name: "Barangay 48-A", fee: 43 },
            { name: "Barangay 49", fee: 43 },
            { name: "Barangay 49-A", fee: 43 },
            { name: "Barangay 5", fee: 43 },
            { name: "Barangay 50", fee: 43 },
            { name: "Barangay 51", fee: 43 },
            { name: "Barangay 52", fee: 43 },
            { name: "Barangay 53", fee: 43 },
            { name: "Barangay 53-A", fee: 43 },
            { name: "Barangay 53-B", fee: 43 },
            { name: "Barangay 54", fee: 43 },
            { name: "Barangay 54-A", fee: 43 },
            { name: "Barangay 55", fee: 43 },
            { name: "Barangay 56", fee: 43 },
            { name: "Barangay 57", fee: 43 },
            { name: "Barangay 58-A", fee: 43 },
            { name: "Barangay 59", fee: 43 },
            { name: "Barangay 6", fee: 43 },
            { name: "Barangay 60", fee: 43 },
            { name: "Barangay 61", fee: 43 },
            { name: "Barangay 62", fee: 43 },
            { name: "Barangay 62-A", fee: 43 },
            { name: "Barangay 62-B", fee: 43 },
            { name: "Barangay 7", fee: 43 },
            { name: "Barangay 8", fee: 43 },
            { name: "Barangay 9", fee: 43 }
        ]
        
    },
    {
        city: "Indang",
        barangays: [
            { name: "Bancod", fee: 44 },
            { name: "Barangay 1", fee: 44 },
            { name: "Barangay 2", fee: 44 },
            { name: "Barangay 3", fee: 44 },
            { name: "Barangay 4", fee: 44 },
            { name: "Buna Cerca", fee: 44 },
            { name: "Buna Lejos 1", fee: 44 },
            { name: "una Lejos 2", fee: 44 },
            { name: "Calumpang Cerca", fee: 44 },
            { name: "Calumpang Lejos 1", fee: 44 },
            { name: "Carasuchi", fee: 44 },
            { name: "Daine 1", fee: 44 },
            { name: "Daine 2", fee: 44 },
            { name: "Guyam Malaki", fee: 44 },
            { name: "Guyam Munti", fee: 44 },
            { name: "Harasan", fee: 44 },
            { name: "Kayquit 1", fee: 44 },
            { name: "Kayquit 2", fee: 44 },
            { name: "Kayquit 3", fee: 44 },
            { name: "Kaytapos", fee: 44 },
            { name: "Limbon", fee: 44 },
            { name: "Lumampong Balagbag", fee: 44 },
            { name: "Lumampong Halayhay", fee: 44 },
            { name: "Mahabangkahoy Cerca", fee: 44 },
            { name: "Mahabangkahoy Lejos", fee: 44 },
            { name: "Mataas na Lupa", fee: 44 },
            { name: "Pulo", fee: 44 },
            { name: "Tambo Balagbag", fee: 44 },
            { name: "Tambo Ilaya", fee: 44 },
            { name: "Tambo Kulit", fee: 44 },
            { name: "Tambo Malaki", fee: 44 }

        ]
    },
    {
        city: "Silang",
        barangays: [
            { name: "Acacia", fee: 45 },
            { name: "Adlas", fee: 45 },
            { name: "Anahaw 1", fee: 45 },
            { name: "Anahaw 2", fee: 45 },
            { name: "Balite 1", fee: 45 },
            { name: "Balite 2", fee: 45 },
            { name: "Balubad", fee: 45 },
            { name: "Barangay 1", fee: 45 },
            { name: "Barangay 2", fee: 45 },
            { name: "Barangay 3", fee: 45 },
            { name: "Barangay 4", fee: 45 },
            { name: "Barangay 5", fee: 45 },
            { name: "Batas", fee: 45 },
            { name: "Biga 1", fee: 45 },
            { name: "Biga 2", fee: 45 },
            { name: "Biluso", fee: 45 },
            { name: "Bucal", fee: 45 },
            { name: "Buho", fee: 45 },
            { name: "Bulihan", fee: 45 },
            { name: "Cabangan", fee: 45 },
            { name: "Carmen", fee: 45 },
            { name: "Hoyo", fee: 45 },
            { name: "Hukay", fee: 45 },
            { name: "Iba", fee: 45 },
            { name: "Inchican", fee: 45 },
            { name: "Ipil 1", fee: 45 },
            { name: "Kalublob", fee: 45 },
            { name: "Kaong", fee: 45 },
            { name: "Lalaan 1", fee: 45 },
            { name: "Lalaan 2", fee: 45 },
            { name: "Litlit", fee: 45 },
            { name: "Lucsuhin", fee: 45 },
            { name: "Lumil", fee: 45 },
            { name: "Maguyam", fee: 45 },
            { name: "Malaking Tatyao", fee: 45 },
            { name: "Mataas na Burol", fee: 45 },
            { name: "Munting Ilog", fee: 45 },
            { name: "Narra 1", fee: 45 },
            { name: "Narra 2", fee: 45 },
            { name: "Narra 3", fee: 45 },
            { name: "Pagligawan", fee: 45 },
            { name: "Pasong Langka", fee: 45 },
            { name: "Pooc 1", fee: 45 },
            { name: "Pooc 2", fee: 45 },
            { name: "Pulong Bunga", fee: 45 },
            { name: "Pulong Saging", fee: 45 },
            { name: "Puting Kahoy", fee: 45 },
            { name: "Sabutan", fee: 45 },
            { name: "San Miguel 1", fee: 45 },
            { name: "San Miguel 2", fee: 45 },
            { name: "San Vicente 1", fee: 45 },
            { name: "San Vicente 2", fee: 45 },
            { name: "Santol", fee: 45 },
            { name: "Tartaria", fee: 45 },
            { name: "Tibig", fee: 45 },
            { name: "Toledo", fee: 45 },
            { name: "Tubuan 1", fee: 45 },
            { name: "Tubuan 2", fee: 45 },
            { name: "Tubuan 3", fee: 45 },
            { name: "Ulat", fee: 45 },
            { name: "Yakal", fee: 45 }
            

        ]
    },
    {
        city: "Magallanes",
        barangays: [
            { name: "Baliwag", fee: 46 },
            { name: "Barangay 1", fee: 46 },
            { name: "Barangay 2", fee: 46 },
            { name: "Barangay 3", fee: 46 },
            { name: "Barangay 4", fee: 46 },
            { name: "Barangay 5", fee: 46 },
            { name: "Bendita 1", fee: 46 },
            { name: "Bendita 2", fee: 46 },
            { name: "Caluangan", fee: 46 },
            { name: "Kabulusan", fee: 46 },
            { name: "Medina", fee: 46 },
            { name: "Pacheco", fee: 46 },
            { name: "Ramirez", fee: 46 },
            { name: "San Agustin", fee: 46 },
            { name: "Tua", fee: 46 },
            { name: "Urdaneta", fee: 46 }


        ]
    },
    {
        city: "General Emilio Aguinaldo",
        barangays: [
            { name: "A. Dalusag", fee: 39 },
            { name: "Batas Dao", fee: 39 },
            { name: "Castanos Cerca", fee: 39 },
            { name: "Castanos Lejos", fee: 39 },
            { name: "Kabulusan", fee: 39 },
            { name: "Kaymisas", fee: 39 },
            { name: "Kaypaaba", fee: 39 },
            { name: "Lumipa", fee: 39 },
            { name: "Narvaez", fee: 39 },
            { name: "Poblacion 1", fee: 39 },
            { name: "Poblacion 2", fee: 39 },
            { name: "Poblacion 3", fee: 39 },
            { name: "Poblacion 4", fee: 39 },
            { name: "Taboara", fee: 39 }
            
        ]
    },
    {
        city: "Amadeo",
        barangays: [
            { name: "Banaybanay", fee: 38 },
            { name: "Barangay 1", fee: 38 },
            { name: "Barangay 2", fee: 38 },
            { name: "Barangay 3", fee: 38 },
            { name: "Barangay 4", fee: 38 },
            { name: "Barangay 5", fee: 38 },
            { name: "Barangay 6", fee: 38 },
            { name: "Barangay 7", fee: 38 },
            { name: "Barangay 8", fee: 38 },
            { name: "Barangay 9", fee: 38 },
            { name: "Barangay 10", fee: 38 },
            { name: "Barangay 11", fee: 38 },
            { name: "Barangay 12", fee: 38 },
            { name: "Bucal", fee: 38 },
            { name: "Buho", fee: 38 },
            { name: "Dagatan", fee: 38 },
            { name: "Halang", fee: 38 },
            { name: "Loma", fee: 38 },
            { name: "Maitim", fee: 38 },
            { name: "Maymangga", fee: 38 },
            { name: "Minantok Kanluran", fee: 38 },
            { name: "Minantok Silangan", fee: 38 },
            { name: "Pangil", fee: 38 },
            { name: "Salaban", fee: 38 },
            { name: "Talon", fee: 38 },
            { name: "Tamacan", fee: 38 }

            
        ]
    },
    {
        city: "Trece Martires",
        barangays: [
            { name: "Aguado", fee: 47 },
            { name: "Cabezas", fee: 47 },
            { name: "Cabuco", fee: 47 },
            { name: "Conchu", fee: 47 },
            { name: "De Ocampo", fee: 47 },
            { name: "Gregorio", fee: 47 },
            { name: "Inocencio", fee: 47 },
            { name: "Lallana", fee: 47 },
            { name: "Lapidario", fee: 47 },
            { name: "Luciano", fee: 47 },
            { name: "Osorio", fee: 47 },
            { name: "Perez", fee: 47 },
            { name: "San Agustin", fee: 47 }
          
        ]
    },
    {
        city: "Tanza",
        barangays: [
            { name: "Amaya 1", fee: 48 },
            { name: "Amaya 2", fee: 48 },
            { name: "Amaya 3", fee: 48 },
            { name: "Amaya 4", fee: 48 },
            { name: "Amaya 5", fee: 48 },
            { name: "Amaya 6", fee: 48 },
            { name: "Amaya 7", fee: 48 },
            { name: "Bagtas", fee: 48 },
            { name: "Biga", fee: 48 },
            { name: "Biwas", fee: 48 },
            { name: "Bucal", fee: 48 },
            { name: "Bunga", fee: 48 },
            { name: "Calibuyo", fee: 48 },
            { name: "Capipisa", fee: 48 },
            { name: "Daang Amayan 1", fee: 48 },
            { name: "Daang Amayan 2", fee: 48 },
            { name: "Daang Amayan 3", fee: 48 },
            { name: "Halayahay", fee: 48 },
            { name: "Juluan 1", fee: 48 },
            { name: "Juluan 2", fee: 48 },
            { name: "Juluan 3", fee: 48 },
            { name: "Juluan 4", fee: 48 },
            { name: "Juluan 5", fee: 48 },
            { name: "Juluan 6", fee: 48 },
            { name: "Juluan 7", fee: 48 },
            { name: "Juluan 8", fee: 48 },
            { name: "Lambingan", fee: 48 },
            { name: "Mulawin", fee: 48 },
            { name: "Paradahan 1", fee: 48 },
            { name: "Paradahan 2", fee: 48 },
            { name: "Punta 1", fee: 48 },
            { name: "Punta 2", fee: 48 },
            { name: "Sahud Ulan", fee: 48 },
            { name: "Sanja Mayor", fee: 48 },
            { name: "Santol", fee: 48 },
            { name: "Tanauan", fee: 48 },
            { name: "Tres Cruses", fee: 48 }
           
        ]
    },
    {
        city: "General Trias",
        barangays: [
            { name: "Alingaro", fee: 46 },
            { name: "Arnaldo Poblacion", fee: 46 },
            { name: "Bacao 1", fee: 46 },
            { name: "Bacao 2", fee: 46 },
            { name: "Bagumbayan Poblacion", fee: 46 },
            { name: "Biclatan", fee: 46 },
            { name: "Buenavista 1", fee: 46 },
            { name: "Buenavista 2", fee: 46 },
            { name: "Buenavista 3", fee: 46 },
            { name: "Corregidor Poblacion", fee: 46 },
            { name: "Dulong Bayan Poblacion", fee: 46 },
            { name: "Gov. Ferrer Poblacion", fee: 46 },
            { name: "Jalavera", fee: 46 },
            { name: "Manggahan", fee: 46 },
            { name: "Navarro", fee: 46 },
            { name: "Ninety Sixth Poblacion", fee: 46 },
            { name: "Panungyanan", fee: 46 },
            { name: "Pasong Camachille 1", fee: 46 },
            { name: "Pasong Camachille 2", fee: 46 },
            { name: "Pasong Kawayan 1", fee: 46 },
            { name: "Pasong Kawayan 2", fee: 46 },
            { name: "Prinza Poblacion", fee: 46 },
            { name: "Sampalucan Poblacion", fee: 46 },
            { name: "San Francisco", fee: 46 },
            { name: "San Gabriel Poblacion", fee: 46 },
            { name: "San Juan 1", fee: 46 },
            { name: "San Juan 2", fee: 46 },
            { name: "Santa Clara", fee: 46 },
            { name: "Santiago", fee: 46 },
            { name: "Tapia", fee: 46 },
            { name: "Tejero", fee: 46 },
            { name: "Vibora Poblacion", fee: 46 }

        ]
    },
    {
        city: "General Mariano Alvarez",
        barangays: [
            { name: "Aldiano Olaes", fee: 49 },
            { name: "Barangay 1 Poblacion", fee: 49 },
            { name: "Barangay 2 Poblacion", fee: 49 },
            { name: "Barangay 3 Poblacion", fee: 49 },
            { name: "Barangay 4 Poblacion", fee: 49 },
            { name: "Barangay 5 Poblacion", fee: 49 },
            { name: "Benjamin Tirona", fee: 49 },
            { name: "Bernardo Pulido", fee: 49 },
            { name: "Epifanio Malia", fee: 49 },
            { name: "Fiorello Calimag", fee: 49 },
            { name: "Francisco de Castro", fee: 49 },
            { name: "Gavibo Maderan", fee: 49 },
            { name: "Gregoria de Jesus", fee: 49 },
            { name: " Inocencio Salud", fee: 49 },
            { name: "Jacinto Lumberas", fee: 49 },
            { name: "Kapitan Kua", fee: 49 },
            { name: "Koronel Jose P. Elises", fee: 49 },
            { name: "Macario Dacon", fee: 49 },
            { name: "Marcelino Memjie", fee: 49 },
            { name: "Nicolasa Virata", fee: 49 },
            { name: "Pantaleon Granados", fee: 49 },
            { name: "Ramon Cruz", fee: 49 },
            { name: "San Gabriel", fee: 49 },
            { name: "San Jose", fee: 49 },
            { name: "Severino de Las Alas", fee: 49 },
            { name: "Tiniente Tiago", fee: 49 }
           

        ]
    },
    {
        city: "Alfonso",
        barangays: [
            { name: "Amuyong", fee: 50 },
            { name: "Barangay 1", fee: 50 },
            { name: "Barangay 2", fee: 50 },
            { name: "Barangay 3", fee: 50 },
            { name: "Barangay 4", fee: 50 },
            { name: "Barangay 5", fee: 50 },
            { name: "Bilog", fee: 50 },
            { name: "Buck State", fee: 50 },
            { name: "Esperanza Ibaba", fee: 50 },
            { name: "Kaysuyo", fee: 50 },
            { name: "Kaytitinga 1", fee: 50 },
            { name: "Kaytitinga 2", fee: 50 },
            { name: "Kaytitinga 3", fee: 50 },
            { name: "Luksuhin", fee: 50 },
            { name: "Luksuhin Ilaya", fee: 50 },
            { name: "Mangas 1", fee: 50 },
            { name: "Mangas 2", fee: 50 },
            { name: "Marahan 1", fee: 50 },
            { name: "Kaytitinga 1", fee: 50 },
            { name: "Kaytitinga 2", fee: 50 },
            { name: "Kaytitinga 3", fee: 50 },
            { name: "Luksuhin", fee: 50 },
            { name: "Luksuhin Ilaya", fee: 50 },
            { name: "Mangas", fee: 50 },
            { name: "Marahan 1", fee: 50 },
            { name: "Marahan 2", fee: 50 },
            { name: "Matagbak 2", fee: 50 },
            { name: "Pajo", fee: 50 },
            { name: "Santa Teresa", fee: 50 },
            { name: "Sikat", fee: 50 },
            { name: "Sinaliw", fee: 50 },
            { name: "Sinaliw na Munti", fee: 50 },
            { name: " Sulsugin", fee: 50 },
            { name: "Taywanak Ibaba", fee: 50 },
            { name: "Taywanak Ilaya", fee: 50 },
            { name: "Upli", fee: 50 }
   
        ]
    },
    {
        city: "Mendez",
        barangays: [
            { name: "Anuling Cerca 1", fee: 51 },
            { name: "Anuling Cerca 2", fee: 51 },
            { name: "Anuling Lejos 1", fee: 51 },
            { name: "Anuling Lejos 2", fee: 51 },
            { name: "Asis 1", fee: 51 },
            { name: "Asis 2", fee: 51 },
            { name: "Asis 3", fee: 51 },
            { name: "Banayad", fee: 51 },
            { name: "Galicia 1", fee: 51 },
            { name: "Galicia 2", fee: 51 },
            { name: "Galicia 3", fee: 51 },
            { name: "Miguel Mojica", fee: 51 },
            { name: "Palopoc 1", fee: 51 },
            { name: "Palopoc 2", fee: 51 },
            { name: "Panungyan 1", fee: 51 },
            { name: "Panungyan 2", fee: 51 },
            { name: "Poblacion 1", fee: 51 },
            { name: "Poblacion 2", fee: 51 },
            { name: "Poblacion 3", fee: 51 },
            { name: "Poblacion 4", fee: 51 },
            { name: "Poblacion 5", fee: 51 },
            { name: "Poblacion 6", fee: 51 },
            { name: "Poblacion 7", fee: 51 }
         
        ]
    },
    {
        city: "Carmona",
        barangays: [
            { name: "Bancal", fee: 52 },
            { name: "Barangay 1", fee: 52 },
            { name: "Barangay 2", fee: 52 },
            { name: "Barangay 3", fee: 52 },
            { name: "Barangay 4", fee: 52 },
            { name: "Barangay 5", fee: 52 },
            { name: "Barangay 6", fee: 52 },
            { name: "Barangay 7", fee: 52 },
            { name: "Barangay 8", fee: 52 },
            { name: "Cabilang Buhay", fee: 52 },
            { name: "Lantic", fee: 52 },
            { name: "Mabuhay", fee: 52 },
            { name: "Maduya", fee: 52 },
            { name: "Milagroso", fee: 52 }
  
        ]
    },
    {
        city: "Kawit",
        barangays: [
            { name: "Balsahan-Bisita", fee: 53 },
            { name: "Batong Dalig", fee: 53 },
            { name: "Binakayan-Aplaya", fee: 53 },
            { name: "Binakayan-Kanluran", fee: 53 },
            { name: "Congbalay-Legaspi", fee: 53 },
            { name: "Gahak", fee: 53 },
            { name: "Kaingen", fee: 53 },
            { name: "Magdalo", fee: 53 },
            { name: "Manggahan-Lawin", fee: 53 },
            { name: "Marulas", fee: 53 },
            { name: "Panamitan", fee: 53 },
            { name: "Pulvorista", fee: 53 },
            { name: "Samala-Marquez", fee: 53 },
            { name: "San Sebastian", fee: 53 },
            { name: "Santa Isabel", fee: 53 },
            { name: "Tabon 1", fee: 53 },
            { name: "Tabon 2", fee: 53 },
            { name: "Tabon 3", fee: 53 },
            { name: "Toclong", fee: 53 },
            { name: "Tramo-Bantayan", fee: 53 },
            { name: "Wakas 1", fee: 53 },
            { name: "Wakas 2", fee: 53 }
           

          
        ]
    },
    {
        city: "Maragondon",
        barangays: [
            { name: "Bucal 1", fee: 53 },
            { name: "Bucal 2", fee: 53 },
            { name: "Bucal 3A", fee: 53 },
            { name: "Bucal 4A", fee: 53 },
            { name: "Caingin Poblacion", fee: 53 },
            { name: "Garita 1A", fee: 53 },
            { name: "Garita 1B", fee: 53 },
            { name: "Layong Mabilog", fee: 53 },
            { name: "Pantihhan 1", fee: 53 },
            { name: "Pantihhan 2", fee: 53 },
            { name: "Pantihhan 3", fee: 53 },
            { name: "Pantihhan 4", fee: 53 },
            { name: "Patungan", fee: 53 },
            { name: "Pinagsanhan 1A", fee: 53 },
            { name: "Pinagsanhan 1B", fee: 53 },
            { name: "Poblacion 1A", fee: 53 },
            { name: "Poblacion 1B", fee: 53 }

           
        ]
    },
    {
        city: "Ternate",
        barangays: [
            { name: "Bucana", fee: 54 },
            { name: "Poblacion 1", fee: 54 },
            { name: "Poblacion 1-A", fee: 54 },
            { name: "Poblacion 2", fee: 54 },
            { name: "Poblacion 3", fee: 54 },
            { name: "San Jose", fee: 54 },
            { name: "San Juan 1", fee: 54 },
            { name: "San Juan 2", fee: 54 },
            { name: "San Juan 3", fee: 54 },
            { name: "Sapang 1", fee: 54 },
            { name: "Sapang 2", fee: 54 }
   
        ]
    },
    {
        city: "Rosario",
        barangays: [
            { name: "Bagbag 1", fee: 55 },
            { name: "Bagbag 2", fee: 55 },
            { name: "Kanluran", fee: 55 },
            { name: "Ligtong 1", fee: 55 },
            { name: "Ligtong 2", fee: 55 },
            { name: "Ligtong 3", fee: 55 },
            { name: "Ligtong 4", fee: 55 },
            { name: "Muzon 1", fee: 55 },
            { name: "Muzon 2", fee: 55 },
            { name: "Sapa 1", fee: 55 },
            { name: "Sapa 2", fee: 55 },
            { name: "Sapa 3", fee: 55 },
            { name: "Sapa 4", fee: 55 },
            { name: "Silangan 2", fee: 55 },
            { name: "Tejeros Convention", fee: 55 },
            { name: "Wawa 1", fee: 55 },
            { name: "Wawa 2", fee: 55 },
            { name: "Wawa 3", fee: 55 }

         
        ]
    },
    {
        city: "Naic",
        barangays: [
            { name: "Bagong Karsada?", fee: 56 },
            { name: "Balsahan", fee: 56 },
            { name: "Bancaan", fee: 56 },
            { name: "Bucana Malaki", fee: 56 },
            { name: "Calubcob", fee: 56 },
            { name: "Capt. C. Nazareno", fee: 56 },
            { name: "Halang", fee: 56 },
            { name: "Humbak", fee: 56 },
            { name: "Ibayo Estacion", fee: 56 },
            { name: "Ibayo Silangan", fee: 56 },
            { name: "Kanluran", fee: 56 },
            { name: "Labac", fee: 56 },
            { name: "Lactoria", fee: 56 },
            { name: "Mabolo", fee: 56 },
            { name: "Makina", fee: 56 },
            { name: "Malainen Bago", fee: 56 },
            { name: "Malainen Luma", fee: 56 },
            { name: "Molino", fee: 56 },
            { name: "Palangue 1", fee: 56 },
            { name: "Palangue 2 & 3", fee: 56 },
            { name: "Sabang", fee: 56 },
            { name: "San Roque", fee: 56 },
            { name: "Santulan", fee: 56 },
            { name: "Sapan", fee: 56 },
            { name: "Timbalan Balsahan", fee: 56 },
            { name: "Timbalan Conception", fee: 56 }
        

           
        ]
    },
    {
        city: "Noveleta",
        barangays: [
            { name: "Magdiwag", fee: 57 },
            { name: "Poblacion", fee: 57 },
            { name: "Salcedo I", fee: 57 },
            { name: "Salcedo II", fee: 57 },
            { name: "San Antonio I", fee: 57 },
            { name: "San Antonio II", fee: 57 },
            { name: "San Jose I", fee: 57 },
            { name: "San Jose II", fee: 57 },
            { name: "San Juan I", fee: 57 },
            { name: "San Rafael I", fee: 57 },
            { name: "San Rafael II", fee: 57 },
            { name: "San Rafael III", fee: 57 },
            { name: "San Rafael IV", fee: 57 },
            { name: "Santa Rosa I", fee: 57 },
            { name: "Santa Rosa II", fee: 57 }
           
        ]
    },
    {
        city: "Tagaytay",
        barangays: [
            { name: "Asisan", fee: 58 },
            { name: "Bagong Tubig", fee: 58 },
            { name: "Calabuso", fee: 58 },
            { name: "Dapdap West", fee: 58 },
            { name: "Dapdap Eest", fee: 58 },
            { name: "Francisco", fee: 58 },
            { name: "Guinhawa East", fee: 58 },
            { name: "Guinhawa South", fee: 58 },
            { name: "Iruhin East", fee: 58 },
            { name: "Iruhin South", fee: 58 },
            { name: "Kaybagal East", fee: 58 },
            { name: "Kaybagal North", fee: 58 },
            { name: "Kaybagal South", fee: 58 },
            { name: "Mag-Asawang LLat", fee: 58 },
            { name: "Maharlika East", fee: 58 },
            { name: "Maharlika West", fee: 58 },
            { name: "Maitim 2nd Central", fee: 58 },
            { name: "Maitim 2nd East", fee: 58 },
            { name: "Maitim 2nd West", fee: 58 },
            { name: "Mendez Crossing East", fee: 58 },
            { name: "Mendez Crossing West", fee: 58 },
            { name: "Neogan", fee: 58 },
            { name: "Patutong Malaki North", fee: 58 },
            { name: "Patutong Malaki South", fee: 58 },
            { name: "Sungay North", fee: 58 },
            { name: "Sungay South", fee: 58 },
            { name: "Tolentino East", fee: 58 },
            { name: "Tolentino West", fee: 58 },
            { name: "Zambal", fee: 58 }
         
           
        ]
    },

    
  ];

module.exports = shippingFees